import bus from './Images/bus.png';
import busBlue from './Images/busBlue.png';
import bed from './Images/bed.png';
import home from './Images/home.png';
import homeBlue from './Images/homeBlue.png';
import homeGrey from './Images/homeGrey.png';
import homeOrange from './Images/homeOrange.png';
import hotel from './Images/hotel.png';
import hotelBlue from './Images/hotelBlue.png';
import luggage from './Images/luggage.png';
import luggageBlue from './Images/luggageBlue.png';
import luggageGrey from './Images/luggageGrey.png';
import luggageOrange from './Images/luggageOrange.png';
import user from './Images/user.png';
import plane from './Images/plane.png';
import planeBlue from './Images/planeBlue.png';
import userBlue from './Images/userBlue.png';
import userOrange from './Images/userOrange.png';
import userGrey from './Images/userGrey.png';
import landing from './Images/landing.png';
import takeoff from './Images/takeoff.png';
import location from './Images/location.png';
import plus from './Images/plus.png';
import minus from './Images/minus.png';
import next from './Images/next.png';
import prev from './Images/back.png';
import close from './Images/close.png';
import userWhite from './Images/userWhite.png';
import exit from './Images/exit.png'
const images = {'logout':exit,'userWhite':userWhite,'close':close,'next':next,'prev':prev,'landing':landing,'takeoff':takeoff,'location':location,'plus':plus,'minus':minus,'bus':bus,'busBlue':busBlue,'bed':bed,'home':home,'homeBlue':homeBlue,'homeGrey':homeGrey,'homeOrange':homeOrange,'hotel':hotel,'hotelBlue':hotelBlue,'luggage':luggage,'luggaeBlue':luggageBlue,'luggageGrey':luggageGrey,'luggageOrange':luggageOrange,'plane':plane,'planeBlue':planeBlue,'user':user,'userBlue':userBlue,'userOrange':userOrange,'userGrey':userGrey}

export default images;